stages:
    - build
    - test
    - deploy

buildcontainers:
    stage: build
    script: git submodule init && git submodule update --remote && docker-compose -f docker/docker-compose.yml up -d && composer install -n --prefer-dist

phptest:
    stage: test
    script: ./docker/workspace.sh vendor/bin/phpunit --bootstrap vendor/autoload.php tests
